name: "🚨 iStaging Asia 이슈"
description: 프로덕션의 이슈를 등록하고 관리합니다.
labels: ["production"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 프로덕션 이슈 등록
        > 어떤 문제점이 발생했는지 자세히 기록해 주세요.

  - type: textarea
    id: description
    attributes:
      label: |
      "문제점 (Description)"
      
      placeholder: "예: 로그인 버튼을 눌러도 반응이 없으며, 콘솔에 500 에러가 표시됩니다.\n 하단의 작업자와 이슈 종류를 지정해주세요."
    validations:
      required: true
